version: '3'
services:
  postgres_service_core:
    container_name: postgres_bank_line
    image: 'postgres:13-alpine'
    restart: always
    environment:
      - POSTGRES_DB=bank_line
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
      - ./config.sql:/docker-entrypoint-initdb.d/config.sql
    networks:
      - cee-net

networks:
  cee-net:
    driver: bridge
